### PR TITLE
Fix error with surrogate characters in strftime

### PR DESCRIPTION
**Pull request by pganssle**
This fixes the bug and updates the tests.

### CODE REVIEW

**Comment by pganssle** [comment]
I'm not a core dev so I can't push directly to your branch.

**Comment by izbyshev** [comment]
@pganssle Thank you for actually fixing the problem! Would you prefer to add tests and merge it separately as the PR for bpo-34481 or combine our PRs and fix both issues at the same time?

**Comment by pganssle** [comment]
Doesn't really matter to me, but thinking about it more, we should probably do it as two separate PRs (I'll wait for yours to get merged), so that I can easily update it in response to review comments.

**Comment by izbyshev** [comment]
@pganssle You also need to handle `PyUnicode_AsUTF8AndSize()` inside the loop (for `"%Z"`), otherwise, `strftime` may still fail:
```
>>> import datetime as dt
>>> tzinfo = dt.timezone(dt.timedelta(), '\ud800')
>>> t = dt.time(tzinfo=tzinfo)
>>> t.strftime("%Z")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud800' in position 0: surrogates not allowed
```

**Pull request closed without merging**
